routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/**** expenses ***********/

    Route::resource('expense-users','ExpenseUsersController');

    Route::get('download/{file?}','ExpenseUsersController@download')->name('download');

app/Models/ExpenseUser.php
<?php

namespace App\Models;

use DateTimeInterface;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class ExpenseUser extends Model
{
    protected $table = 'expense_users';

    protected $casts = [
        'created_at' => 'datetime:Y-m-d H:i:s',
        'updated_at' => 'datetime:Y-m-d H:i:s',
    ];

    protected $fillable = [
        'user_id', 'title','amount','attachment','date','status'
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function scopeUserPermission($query)
    {
        if(auth()->user()->type !== "manager"){
            return $query->where('user_id', auth()->id());
        }
    }

}

app/Http/Controllers/ExpenseUsersController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ExpenseUserRequest;
use App\Models\ExpenseUser;
use Illuminate\Support\Facades\Gate;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Response;
use Illuminate\View\View;
use Symfony\Component\HttpFoundation\BinaryFileResponse;

class ExpenseUsersController extends Controller
{
    /**
     * get custom value from relation
     *
     * @var string[]
     */
    protected $relations = ['user:id,name'];

    /**
     * validation use all function by auth user
     * ExpenseUsersController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * use locale scope userPermission
     * @return View
     */
    public function index()
    {
        $expenseUsers = ExpenseUser::with($this->relations)->userPermission()->get();
        return view('expense_users.index', compact('expenseUsers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|Response|View
     */
    public function create()
    {
        $expenseUsers = ExpenseUser::with($this->relations);
        Gate::authorize('expense-create', $expenseUsers);
        return view('expense_users.create');
    }

    /**
     * Create a new User Expenses OR Update Expenses When have id.
     *
     * @param ExpenseUserRequest $request
     * @return RedirectResponse
     */
    public function store(ExpenseUserRequest $request)
    {
        $userExpense = new ExpenseUser();

        if ($files = $request->file('attachment')) {
            $fileName = date('YmdHis') . "." . $files->getClientOriginalExtension();
            $request->attachment->move(public_path('uploads'), $fileName);
            $userExpense->attachment    = $fileName;
        }

        $userExpense->title        = $request->title;
        $userExpense->user_id       = auth()->user()->id;
        $userExpense->amount        = $request->amount;
        $userExpense->date          = $request->date;
        $userExpense->status        = 0;

        $userExpense->save();

        if ($userExpense) {
            return redirect()->back()->with('success', "add Expenses");
        }
    }

    /**
     *
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Application|Factory|Response|View
     */
    public function show($id)
    {
        $expense_user = ExpenseUser::with($this->relations)->find($id);
        return view('expense_users.show', compact('expense_user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Application|Factory|Response|View
     */
    public function edit($id)
    {
        $expends = Expenses::pluck('name','id');
        $expense_user = ExpenseUser::find($id);
        $option = ['0'=>'in progress','1'=>'approved','2'=>'rejected','3'=>'cancel'];
        if(auth()->user()->type === "employee"){
            unset($option[0]);
            unset($option[1]);
            unset($option[2]);
        }else{
            unset($option[3]);
        }
        return view('expense_users.edit', compact('expends','expense_user','option'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ExpenseUserRequest $request
     * @param int $id
     * @return RedirectResponse
     */
    public function update(ExpenseUserRequest $request, $id)
    {
        $expense_user = ExpenseUser::find($id);

        if ($files = $request->file('attachment')) {
            unlink(public_path('uploads/'.$expense_user->attachment));
            $fileName = date('YmdHis') . "." . $files->getClientOriginalExtension();
            $request->attachment->move(public_path('uploads'), $fileName);
            $expense_user->attachment    = $fileName;
        }

        $expense_user->title         = $request->title;
        $expense_user->user_id       = auth()->id();
        $expense_user->amount        = $request->amount;
        $expense_user->date          = $request->date;
        $expense_user->status        = $request->status;

        $expense_user->save();
        if ($expense_user) {
            return redirect()->back()->with('success', "updated Expenses");
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return RedirectResponse
     */
    public function destroy($id)
    {
        $expense_user = ExpenseUser::find($id);
        if(($expense_user->attachment !== Null) && is_file(public_path($expense_user->attachment))) {
            unlink(public_path('uploads/'.$expense_user->attachment));
        }
        $expense_user->delete();

        return redirect()->back()->with('success', "deleted Expenses");
    }

    /**
     * return file download
     *
     * @param $file_name
     * @return BinaryFileResponse
     */
    public function download($file_name)
    {
        $file_path = public_path('uploads/'.$file_name);
        return response()->download($file_path);
    }
}

resources/views/expense_users/create.blade.php
@extends('layouts.layout')
@inject('model','App\Models\ExpenseUser')
@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <br>
    <br>
    @include('layouts.flash-message')
    <div class="box">
        <div class="box-body">

            {!! Form::model($model,[
              'action' => 'ExpenseUsersController@store',
              'enctype' => 'multipart/form-data',
            ]) !!}

            <div class="col">
                @include('expense_users/form')
                <div class="clearfix"></div>
                <div class="form-group">
                <br>
                <button class="btn btn-primary" type="submit">Save</button>
            </div>


            {!! Form::close() !!}
        </div>
        </div>
        </div>
    </div>



@endsection

resources/views/expense_users/edit.blade.php
@extends('layouts.layout')
@inject('model','App\Models\ExpenseUser')
@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <br>
    <br>
    @include('layouts.flash-message')
    <div class="box">
        <div class="box-body">

            {!! Form::model($expense_user, ['method' => 'PATCH','route' => ['expense-users.update', $expense_user->id]]) !!}
            <input type="hidden" value="update" name="type" class="form-data-input">
            <div class="col">
                @include('expense_users/form')
                <div class="form-group col-md-10">
                    <label for="inputProjectLeader">Status</label>
                    {{ Form::select('status', $option, null, array('class'=>'form-control select2', 'placeholder'=>'choose')) }}
                </div>
                <div class="clearfix"></div>
                <div class="form-group">
                    <br>
                    <button class="btn btn-primary" type="submit">Save</button>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
    </div>



@endsection

resources/views/expense_users/form.blade.php
<style>
    .image-upload>input {
        display: none;
    }
</style>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">بيانات عامة</h3>
                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="form-group col-md-10">
                            <label for="inputName">Title</label>
                            {!! Form::text('title',null,['class' => 'form-control']) !!}
                        </div>
                        <div class="form-group col-md-10">
                            <label for="inputName">Amount</label>
                            {!! Form::number('amount',null,['class' => 'form-control']) !!}
                        </div>
                        <div class="form-group col-md-10">
                            <label for="inputName">Attachment</label><br>
                            {!! Form::file('attachment')!!}
                        </div>
                        <div class="form-group col-md-10">
                            <label for="inputName">Date</label><br>
                            {!!  Form::date('date') !!}
                        </div>

</div>
</div>
<!-- /.card-body -->
</div>
<!-- /.card -->
</div>
</div>
</section>
<!-- /.content -->

resources/views/expense_users/index.blade.php
@extends('layouts.layout')
@section('title')
    Expenses User
@endsection
@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/"><i class="fa fa-dashboard"></i>
                            </a></li>
                        <li class="breadcrumb-item active"> <a href="{{url('expense-users/create')}}" class="btn btn-success"><i class="fa fa-plus-circle"></i></a><li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <br>
    <br>
    <div class="box-body">
        <div class="card">
            <!-- /.card-header -->
            <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                    <tr>
                            <th>#</th>
                            <th>user</th>
                            <th>Expense</th>
                            <th>Amount</th>
                            <th>Attachment</th>
                            <th>Status</th>
                            <th>Date</th>
                            <th>Action</th>

                    </tr>
                    </thead>
                    <tbody>
                    @if(count($expenseUsers))
                        @foreach($expenseUsers as $expense)

                            <tr>
                                <td>{{$expense->id}}</td>
                                <td>{{$expense->user->name}}</td>
                                <td>{{$expense->title}}</td>
                                <td>{{$expense->amount}}</td>
                                <td><a href="{{ route('download',$expense->attachment) }}" target="_blank">{{ $expense->attachment }}</a></td>
                                <td>
                                    @if($expense->status == 0)
                                        <i class="btn btn-info">in progress</i>
                                    @elseif($expense->status == 1)
                                        <i class="btn btn-success">Approved</i>
                                    @else
                                        <i class="btn btn-danger">Rejected</i>
                                    @endif
                                </td>
                                <td>{{ $expense->date }}</td>
                                <td>
                                    <a href="{{url('expense-users/'.$expense->id)}}" class="btn btn-success"><i class="fa fa-eye"></i></a>
                                    <a href="{{url('expense-users/'.$expense->id.'/edit')}}" class="btn btn-warning"><i class="fa fa-edit"></i></a>
                                    <form action="{{ route('expense-users.destroy',$expense->id) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i></button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    @else
                        <div class="alert alert-warning alert-block">
                            <strong>NO Data</strong>
                        </div>
                    @endif
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>

@endsection

resources/views/expense_users/show.blade.php
@extends('layouts.layout')
@section('title')
    Expenses
@endsection
@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/"><i class="fa fa-dashboard"></i> {{__('lang.master')}}
                            </a></li>
                        <li class="breadcrumb-item active"><li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <br>
    <br>
    <div class="box-body">
        <div class="card">
            <!-- /.card-header -->
            <div class="card-body">

                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>User Name:</strong>
                            {{$expense_user->user->name}}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>Expense Name:</strong>
                            {{$expense_user->expense->name}}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>amount:</strong>
                            {{$expense_user->amount}}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>date:</strong>
                            {{$expense_user->date}}

                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>attachment:</strong>
                            <a href="{{ route('download',$expense_user->attachment) }}" target="_blank">{{ $expense_user->attachment }}</a>
                        </div>
                    </div>

                </div>
            </div>
        </div>
@endsection